# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 658)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1041, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.create_script_tab = QtWidgets.QWidget()
        self.create_script_tab.setObjectName("create_script_tab")
        self.widget = QtWidgets.QWidget(self.create_script_tab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1031, 571))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.installerComponnentLabel = QtWidgets.QLabel(self.widget)
        self.installerComponnentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.installerComponnentLabel.setObjectName("installerComponnentLabel")
        self.verticalLayout.addWidget(self.installerComponnentLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openInstallerButton = QtWidgets.QPushButton(self.widget)
        self.openInstallerButton.setObjectName("openInstallerButton")
        self.horizontalLayout.addWidget(self.openInstallerButton)
        self.refreshListButton = QtWidgets.QPushButton(self.widget)
        self.refreshListButton.setObjectName("refreshListButton")
        self.horizontalLayout.addWidget(self.refreshListButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.treeWidget = QtWidgets.QTreeWidget(self.widget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Запущені програми")
        self.verticalLayout.addWidget(self.treeWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.proprtyComponnentLabel = QtWidgets.QLabel(self.widget)
        self.proprtyComponnentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.proprtyComponnentLabel.setObjectName("proprtyComponnentLabel")
        self.verticalLayout_5.addWidget(self.proprtyComponnentLabel)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.verticalLayout_5.addWidget(self.tableWidget_3)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scriptLabel = QtWidgets.QLabel(self.widget)
        self.scriptLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scriptLabel.setObjectName("scriptLabel")
        self.verticalLayout_4.addWidget(self.scriptLabel)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_4.addWidget(self.textEdit)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.tabWidget.addTab(self.create_script_tab, "")
        self.host_manager_tab = QtWidgets.QWidget()
        self.host_manager_tab.setObjectName("host_manager_tab")
        self.widget1 = QtWidgets.QWidget(self.host_manager_tab)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 1021, 561))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.localMachineListLabel = QtWidgets.QLabel(self.widget1)
        self.localMachineListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.localMachineListLabel.setObjectName("localMachineListLabel")
        self.verticalLayout_2.addWidget(self.localMachineListLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.updateHostListButton = QtWidgets.QPushButton(self.widget1)
        self.updateHostListButton.setObjectName("updateHostListButton")
        self.horizontalLayout_2.addWidget(self.updateHostListButton)
        self.startInstalationButton = QtWidgets.QPushButton(self.widget1)
        self.startInstalationButton.setObjectName("startInstalationButton")
        self.horizontalLayout_2.addWidget(self.startInstalationButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.hostListTableWidget = QtWidgets.QTableWidget(self.widget1)
        self.hostListTableWidget.setObjectName("hostListTableWidget")
        self.hostListTableWidget.setColumnCount(4)
        self.hostListTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hostListTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostListTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostListTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostListTableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.hostListTableWidget)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ScriptListLabel = QtWidgets.QLabel(self.widget1)
        self.ScriptListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ScriptListLabel.setObjectName("ScriptListLabel")
        self.verticalLayout_3.addWidget(self.ScriptListLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addNewScriptButton = QtWidgets.QPushButton(self.widget1)
        self.addNewScriptButton.setObjectName("addNewScriptButton")
        self.horizontalLayout_3.addWidget(self.addNewScriptButton)
        self.removeScriptButton = QtWidgets.QPushButton(self.widget1)
        self.removeScriptButton.setObjectName("removeScriptButton")
        self.horizontalLayout_3.addWidget(self.removeScriptButton)
        self.editScriptButton = QtWidgets.QPushButton(self.widget1)
        self.editScriptButton.setObjectName("editScriptButton")
        self.horizontalLayout_3.addWidget(self.editScriptButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.scriptListTableWidget = QtWidgets.QTableWidget(self.widget1)
        self.scriptListTableWidget.setObjectName("scriptListTableWidget")
        self.scriptListTableWidget.setColumnCount(2)
        self.scriptListTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.scriptListTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.scriptListTableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.scriptListTableWidget)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.host_manager_tab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1059, 20))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.openInstallerButton)
        MainWindow.setTabOrder(self.openInstallerButton, self.refreshListButton)
        MainWindow.setTabOrder(self.refreshListButton, self.treeWidget)
        MainWindow.setTabOrder(self.treeWidget, self.tableWidget_3)
        MainWindow.setTabOrder(self.tableWidget_3, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.updateHostListButton)
        MainWindow.setTabOrder(self.updateHostListButton, self.startInstalationButton)
        MainWindow.setTabOrder(self.startInstalationButton, self.hostListTableWidget)
        MainWindow.setTabOrder(self.hostListTableWidget, self.addNewScriptButton)
        MainWindow.setTabOrder(self.addNewScriptButton, self.removeScriptButton)
        MainWindow.setTabOrder(self.removeScriptButton, self.editScriptButton)
        MainWindow.setTabOrder(self.editScriptButton, self.scriptListTableWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.installerComponnentLabel.setText(_translate("MainWindow", "Компоненти інсталятора"))
        self.openInstallerButton.setText(_translate("MainWindow", "Open"))
        self.refreshListButton.setText(_translate("MainWindow", "Оновити список"))
        self.proprtyComponnentLabel.setText(_translate("MainWindow", "Властивості компонента"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Назва"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значення"))
        self.scriptLabel.setText(_translate("MainWindow", "Скріпт"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.create_script_tab), _translate("MainWindow", "Створення сценаріїв"))
        self.localMachineListLabel.setText(_translate("MainWindow", "Список локальних машин"))
        self.updateHostListButton.setText(_translate("MainWindow", "Оновлення"))
        self.startInstalationButton.setText(_translate("MainWindow", "Запуск"))
        item = self.hostListTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Назва хоста"))
        item = self.hostListTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP"))
        item = self.hostListTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Статус"))
        item = self.hostListTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Для запуска"))
        self.ScriptListLabel.setText(_translate("MainWindow", "Список сценаріїв"))
        self.addNewScriptButton.setText(_translate("MainWindow", "Додати"))
        self.removeScriptButton.setText(_translate("MainWindow", "Видалити"))
        self.editScriptButton.setText(_translate("MainWindow", "Редагувати"))
        item = self.scriptListTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Назва сценарія"))
        item = self.scriptListTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Для запуска"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.host_manager_tab), _translate("MainWindow", "Менеджер локальних машин"))

