# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app\view_ui\create_script.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1042, 570)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1040, 568))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.componentVerticalLayout = QtWidgets.QVBoxLayout()
        self.componentVerticalLayout.setObjectName("componentVerticalLayout")
        self.componentButtonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.componentButtonsHorizontalLayout.setObjectName("componentButtonsHorizontalLayout")
        self.installerComponentLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.installerComponentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.installerComponentLabel.setObjectName("installerComponentLabel")
        self.componentButtonsHorizontalLayout.addWidget(self.installerComponentLabel)
        self.openInstallerButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openInstallerButton.setIcon(icon)
        self.openInstallerButton.setIconSize(QtCore.QSize(27, 27))
        self.openInstallerButton.setAutoRaise(True)
        self.openInstallerButton.setObjectName("openInstallerButton")
        self.componentButtonsHorizontalLayout.addWidget(self.openInstallerButton)
        self.refreshListButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/full-update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshListButton.setIcon(icon1)
        self.refreshListButton.setIconSize(QtCore.QSize(27, 27))
        self.refreshListButton.setCheckable(False)
        self.refreshListButton.setAutoRepeat(False)
        self.refreshListButton.setAutoRaise(True)
        self.refreshListButton.setObjectName("refreshListButton")
        self.componentButtonsHorizontalLayout.addWidget(self.refreshListButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.componentButtonsHorizontalLayout.addItem(spacerItem)
        self.componentVerticalLayout.addLayout(self.componentButtonsHorizontalLayout)
        self.installerComponentTreeWidget = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents)
        self.installerComponentTreeWidget.setObjectName("installerComponentTreeWidget")
        self.installerComponentTreeWidget.headerItem().setText(0, "Компоненти інсталятора")
        self.componentVerticalLayout.addWidget(self.installerComponentTreeWidget)
        self.proprtyComponentLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.proprtyComponentLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.proprtyComponentLabel.setObjectName("proprtyComponentLabel")
        self.componentVerticalLayout.addWidget(self.proprtyComponentLabel)
        self.proprtyComponentTableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.proprtyComponentTableWidget.setObjectName("proprtyComponentTableWidget")
        self.proprtyComponentTableWidget.setColumnCount(2)
        self.proprtyComponentTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.proprtyComponentTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.proprtyComponentTableWidget.setHorizontalHeaderItem(1, item)
        self.componentVerticalLayout.addWidget(self.proprtyComponentTableWidget)
        self.gridLayout_2.addLayout(self.componentVerticalLayout, 0, 0, 1, 1)
        self.ScriptsVerticalLayout = QtWidgets.QVBoxLayout()
        self.ScriptsVerticalLayout.setObjectName("ScriptsVerticalLayout")
        self.scriptLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.scriptLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scriptLabel.setObjectName("scriptLabel")
        self.ScriptsVerticalLayout.addWidget(self.scriptLabel)
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setObjectName("textEdit")
        self.ScriptsVerticalLayout.addWidget(self.textEdit)
        self.gridLayout_2.addLayout(self.ScriptsVerticalLayout, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.installerComponentLabel.setText(_translate("Form", "Компоненти інсталятора"))
        self.openInstallerButton.setToolTip(_translate("Form", "Відкрити інсталятор"))
        self.openInstallerButton.setText(_translate("Form", "..."))
        self.refreshListButton.setText(_translate("Form", "..."))
        self.proprtyComponentLabel.setText(_translate("Form", "Властивості компонента"))
        item = self.proprtyComponentTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Назва"))
        item = self.proprtyComponentTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Значення"))
        self.scriptLabel.setText(_translate("Form", "Скріпт"))

import app.view_py.view_rc
