# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app\view_ui\host_manager.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1032, 572)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1031, 571))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hostManagerTabGridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.hostManagerTabGridLayout.setObjectName("hostManagerTabGridLayout")
        self.scriptsListVerticalLayout = QtWidgets.QVBoxLayout()
        self.scriptsListVerticalLayout.setObjectName("scriptsListVerticalLayout")
        self.ScriptListLabel = QtWidgets.QLabel(self.layoutWidget)
        self.ScriptListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ScriptListLabel.setObjectName("ScriptListLabel")
        self.scriptsListVerticalLayout.addWidget(self.ScriptListLabel)
        self.scriptsListButtonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.scriptsListButtonsHorizontalLayout.setObjectName("scriptsListButtonsHorizontalLayout")
        self.addNewScriptButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addNewScriptButton.setObjectName("addNewScriptButton")
        self.scriptsListButtonsHorizontalLayout.addWidget(self.addNewScriptButton)
        self.removeScriptButton = QtWidgets.QPushButton(self.layoutWidget)
        self.removeScriptButton.setObjectName("removeScriptButton")
        self.scriptsListButtonsHorizontalLayout.addWidget(self.removeScriptButton)
        self.editScriptButton = QtWidgets.QPushButton(self.layoutWidget)
        self.editScriptButton.setObjectName("editScriptButton")
        self.scriptsListButtonsHorizontalLayout.addWidget(self.editScriptButton)
        self.updateScriptsListPushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.updateScriptsListPushButton.setObjectName("updateScriptsListPushButton")
        self.scriptsListButtonsHorizontalLayout.addWidget(self.updateScriptsListPushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.scriptsListButtonsHorizontalLayout.addItem(spacerItem)
        self.scriptsListVerticalLayout.addLayout(self.scriptsListButtonsHorizontalLayout)
        self.scriptListTableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.scriptListTableWidget.setObjectName("scriptListTableWidget")
        self.scriptListTableWidget.setColumnCount(2)
        self.scriptListTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.scriptListTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.scriptListTableWidget.setHorizontalHeaderItem(1, item)
        self.scriptsListVerticalLayout.addWidget(self.scriptListTableWidget)
        self.hostManagerTabGridLayout.addLayout(self.scriptsListVerticalLayout, 0, 1, 1, 1)
        self.hostListVerticalLayout = QtWidgets.QVBoxLayout()
        self.hostListVerticalLayout.setObjectName("hostListVerticalLayout")
        self.localMachineListLabel = QtWidgets.QLabel(self.layoutWidget)
        self.localMachineListLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.localMachineListLabel.setObjectName("localMachineListLabel")
        self.hostListVerticalLayout.addWidget(self.localMachineListLabel)
        self.hostListButtonsHorizontalLayout = QtWidgets.QHBoxLayout()
        self.hostListButtonsHorizontalLayout.setObjectName("hostListButtonsHorizontalLayout")
        self.fullUpdateHostListButton = QtWidgets.QPushButton(self.layoutWidget)
        self.fullUpdateHostListButton.setObjectName("fullUpdateHostListButton")
        self.hostListButtonsHorizontalLayout.addWidget(self.fullUpdateHostListButton)
        self.updateHostListButton = QtWidgets.QPushButton(self.layoutWidget)
        self.updateHostListButton.setObjectName("updateHostListButton")
        self.hostListButtonsHorizontalLayout.addWidget(self.updateHostListButton)
        self.startInstalationOnHostsButton = QtWidgets.QPushButton(self.layoutWidget)
        self.startInstalationOnHostsButton.setObjectName("startInstalationOnHostsButton")
        self.hostListButtonsHorizontalLayout.addWidget(self.startInstalationOnHostsButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hostListButtonsHorizontalLayout.addItem(spacerItem1)
        self.hostListVerticalLayout.addLayout(self.hostListButtonsHorizontalLayout)
        self.hostListTableWidget = QtWidgets.QTableWidget(self.layoutWidget)
        self.hostListTableWidget.setObjectName("hostListTableWidget")
        self.hostListTableWidget.setColumnCount(4)
        self.hostListTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.hostListTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostListTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostListTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hostListTableWidget.setHorizontalHeaderItem(3, item)
        self.hostListVerticalLayout.addWidget(self.hostListTableWidget)
        self.hostManagerTabGridLayout.addLayout(self.hostListVerticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ScriptListLabel.setText(_translate("Form", "Список сценаріїв"))
        self.addNewScriptButton.setText(_translate("Form", "Додати"))
        self.removeScriptButton.setText(_translate("Form", "Видалити"))
        self.editScriptButton.setText(_translate("Form", "Редагувати"))
        self.updateScriptsListPushButton.setText(_translate("Form", "Оновити список"))
        item = self.scriptListTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Назва сценарія"))
        item = self.scriptListTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Для запуска"))
        self.localMachineListLabel.setText(_translate("Form", "Список локальних машин"))
        self.fullUpdateHostListButton.setText(_translate("Form", "Повне оновлення"))
        self.updateHostListButton.setText(_translate("Form", "Оновлення"))
        self.startInstalationOnHostsButton.setText(_translate("Form", "Запуск"))
        item = self.hostListTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Назва хоста"))
        item = self.hostListTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "IP"))
        item = self.hostListTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Статус"))
        item = self.hostListTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Для запуска"))

