# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app\view_ui\input_network_range.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(308, 118)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 291, 101))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.promtLabel = QtWidgets.QLabel(self.layoutWidget)
        self.promtLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.promtLabel.setObjectName("promtLabel")
        self.verticalLayout.addWidget(self.promtLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ip1_octetLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ip1_octetLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip1_octetLineEdit.sizePolicy().hasHeightForWidth())
        self.ip1_octetLineEdit.setSizePolicy(sizePolicy)
        self.ip1_octetLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.ip1_octetLineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.ip1_octetLineEdit.setObjectName("ip1_octetLineEdit")
        self.horizontalLayout.addWidget(self.ip1_octetLineEdit)
        self.ip1_2_dotLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip1_2_dotLabel.sizePolicy().hasHeightForWidth())
        self.ip1_2_dotLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ip1_2_dotLabel.setFont(font)
        self.ip1_2_dotLabel.setObjectName("ip1_2_dotLabel")
        self.horizontalLayout.addWidget(self.ip1_2_dotLabel)
        self.ip2_octetLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ip2_octetLineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip2_octetLineEdit.sizePolicy().hasHeightForWidth())
        self.ip2_octetLineEdit.setSizePolicy(sizePolicy)
        self.ip2_octetLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.ip2_octetLineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.ip2_octetLineEdit.setObjectName("ip2_octetLineEdit")
        self.horizontalLayout.addWidget(self.ip2_octetLineEdit)
        self.ip2_3_dotLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip2_3_dotLabel.sizePolicy().hasHeightForWidth())
        self.ip2_3_dotLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ip2_3_dotLabel.setFont(font)
        self.ip2_3_dotLabel.setObjectName("ip2_3_dotLabel")
        self.horizontalLayout.addWidget(self.ip2_3_dotLabel)
        self.ip3_octetLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip3_octetLineEdit.sizePolicy().hasHeightForWidth())
        self.ip3_octetLineEdit.setSizePolicy(sizePolicy)
        self.ip3_octetLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.ip3_octetLineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.ip3_octetLineEdit.setObjectName("ip3_octetLineEdit")
        self.horizontalLayout.addWidget(self.ip3_octetLineEdit)
        self.ip3_4_dotLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip3_4_dotLabel.sizePolicy().hasHeightForWidth())
        self.ip3_4_dotLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ip3_4_dotLabel.setFont(font)
        self.ip3_4_dotLabel.setObjectName("ip3_4_dotLabel")
        self.horizontalLayout.addWidget(self.ip3_4_dotLabel)
        self.ip4_octetBeginLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip4_octetBeginLineEdit.sizePolicy().hasHeightForWidth())
        self.ip4_octetBeginLineEdit.setSizePolicy(sizePolicy)
        self.ip4_octetBeginLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.ip4_octetBeginLineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.ip4_octetBeginLineEdit.setObjectName("ip4_octetBeginLineEdit")
        self.horizontalLayout.addWidget(self.ip4_octetBeginLineEdit)
        self.ip4_rangeLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ip4_rangeLabel.sizePolicy().hasHeightForWidth())
        self.ip4_rangeLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ip4_rangeLabel.setFont(font)
        self.ip4_rangeLabel.setObjectName("ip4_rangeLabel")
        self.horizontalLayout.addWidget(self.ip4_rangeLabel)
        self.ip4_octetEndLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.ip4_octetEndLineEdit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.ip4_octetEndLineEdit.setObjectName("ip4_octetEndLineEdit")
        self.horizontalLayout.addWidget(self.ip4_octetEndLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.layoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Діапазон меережі"))
        self.promtLabel.setText(_translate("Dialog", "Введіть діапазон мережі для дослідження"))
        self.ip1_octetLineEdit.setText(_translate("Dialog", "192"))
        self.ip1_2_dotLabel.setText(_translate("Dialog", "."))
        self.ip2_octetLineEdit.setText(_translate("Dialog", "168"))
        self.ip2_3_dotLabel.setText(_translate("Dialog", "."))
        self.ip3_octetLineEdit.setText(_translate("Dialog", "0"))
        self.ip3_4_dotLabel.setText(_translate("Dialog", "."))
        self.ip4_octetBeginLineEdit.setText(_translate("Dialog", "1"))
        self.ip4_rangeLabel.setText(_translate("Dialog", "-"))
        self.ip4_octetEndLineEdit.setText(_translate("Dialog", "255"))

