# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app\view_ui\installer_manager.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1035, 565)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1033, 563))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.installerButtonHorizontalLayout = QtWidgets.QHBoxLayout()
        self.installerButtonHorizontalLayout.setObjectName("installerButtonHorizontalLayout")
        self.installerLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.installerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.installerLabel.setObjectName("installerLabel")
        self.installerButtonHorizontalLayout.addWidget(self.installerLabel)
        self.addInstallerPushButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addInstallerPushButton.setIcon(icon)
        self.addInstallerPushButton.setIconSize(QtCore.QSize(27, 27))
        self.addInstallerPushButton.setCheckable(False)
        self.addInstallerPushButton.setAutoRepeat(False)
        self.addInstallerPushButton.setAutoRaise(True)
        self.addInstallerPushButton.setObjectName("addInstallerPushButton")
        self.installerButtonHorizontalLayout.addWidget(self.addInstallerPushButton)
        self.deleteInstallerPushButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteInstallerPushButton.setIcon(icon1)
        self.deleteInstallerPushButton.setIconSize(QtCore.QSize(27, 27))
        self.deleteInstallerPushButton.setCheckable(False)
        self.deleteInstallerPushButton.setAutoRepeat(False)
        self.deleteInstallerPushButton.setAutoRaise(True)
        self.deleteInstallerPushButton.setObjectName("deleteInstallerPushButton")
        self.installerButtonHorizontalLayout.addWidget(self.deleteInstallerPushButton)
        self.editInstallerPushButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editInstallerPushButton.setIcon(icon2)
        self.editInstallerPushButton.setIconSize(QtCore.QSize(27, 27))
        self.editInstallerPushButton.setCheckable(False)
        self.editInstallerPushButton.setAutoRepeat(False)
        self.editInstallerPushButton.setAutoRaise(True)
        self.editInstallerPushButton.setObjectName("editInstallerPushButton")
        self.installerButtonHorizontalLayout.addWidget(self.editInstallerPushButton)
        self.saveChangesPushButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/database.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveChangesPushButton.setIcon(icon3)
        self.saveChangesPushButton.setIconSize(QtCore.QSize(27, 27))
        self.saveChangesPushButton.setCheckable(False)
        self.saveChangesPushButton.setAutoRepeat(False)
        self.saveChangesPushButton.setAutoRaise(True)
        self.saveChangesPushButton.setObjectName("saveChangesPushButton")
        self.installerButtonHorizontalLayout.addWidget(self.saveChangesPushButton)
        self.updateInstallerListPushButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/full-update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateInstallerListPushButton.setIcon(icon4)
        self.updateInstallerListPushButton.setIconSize(QtCore.QSize(27, 27))
        self.updateInstallerListPushButton.setCheckable(False)
        self.updateInstallerListPushButton.setAutoRepeat(False)
        self.updateInstallerListPushButton.setAutoRaise(True)
        self.updateInstallerListPushButton.setObjectName("updateInstallerListPushButton")
        self.installerButtonHorizontalLayout.addWidget(self.updateInstallerListPushButton)
        self.downInstallerItemButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/arrow_down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downInstallerItemButton.setIcon(icon5)
        self.downInstallerItemButton.setIconSize(QtCore.QSize(27, 27))
        self.downInstallerItemButton.setCheckable(False)
        self.downInstallerItemButton.setAutoRepeat(False)
        self.downInstallerItemButton.setAutoRaise(True)
        self.downInstallerItemButton.setObjectName("downInstallerItemButton")
        self.installerButtonHorizontalLayout.addWidget(self.downInstallerItemButton)
        self.upInstallerItemButton = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/arrow_up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upInstallerItemButton.setIcon(icon6)
        self.upInstallerItemButton.setIconSize(QtCore.QSize(27, 27))
        self.upInstallerItemButton.setCheckable(False)
        self.upInstallerItemButton.setAutoRepeat(False)
        self.upInstallerItemButton.setAutoRaise(True)
        self.upInstallerItemButton.setObjectName("upInstallerItemButton")
        self.installerButtonHorizontalLayout.addWidget(self.upInstallerItemButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.installerButtonHorizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.installerButtonHorizontalLayout, 0, 0, 1, 1)
        self.installerTableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.installerTableWidget.setObjectName("installerTableWidget")
        self.installerTableWidget.setColumnCount(3)
        self.installerTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.installerTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.installerTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.installerTableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.installerTableWidget, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.installerLabel.setText(_translate("Form", "Інсталятори"))
        self.addInstallerPushButton.setToolTip(_translate("Form", "Додати"))
        self.addInstallerPushButton.setText(_translate("Form", "..."))
        self.deleteInstallerPushButton.setToolTip(_translate("Form", "Видалити"))
        self.deleteInstallerPushButton.setText(_translate("Form", "..."))
        self.editInstallerPushButton.setToolTip(_translate("Form", "Редагувати"))
        self.editInstallerPushButton.setText(_translate("Form", "..."))
        self.saveChangesPushButton.setToolTip(_translate("Form", "Збереження списку в базі"))
        self.saveChangesPushButton.setText(_translate("Form", "..."))
        self.updateInstallerListPushButton.setToolTip(_translate("Form", "Оновлення"))
        self.updateInstallerListPushButton.setText(_translate("Form", "..."))
        self.downInstallerItemButton.setToolTip(_translate("Form", "Осутити вниз"))
        self.downInstallerItemButton.setText(_translate("Form", "..."))
        self.upInstallerItemButton.setToolTip(_translate("Form", "Підняти вгори"))
        self.upInstallerItemButton.setText(_translate("Form", "..."))
        item = self.installerTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Назва"))
        item = self.installerTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Шлях"))
        item = self.installerTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Аргументи"))

import app.view_py.view_rc
