ACTIONS = {
    'Close',
    'Click',
    'ClickInput',
    'CloseClick',
    'DoubleClick',
    'DoubleClickInput',
    'DragMouse',
    'DrawOutline',
    'Maximize',
    'Minimize',
    'MoveMouse',
    'MoveWindow',
    'PressMouse',
    'PressMouseInput',
    'ReleaseMouse',
    'ReleaseMouseInput',
    'Restore',
    'RightClick',
    'RightClickInput',
    'SetFocus',
    'Select',
    'Collapse',
    'Expand',
}

EXTENDED_ACTIONS = {
    'Application.Start',
    'Application.Connect',
}
